### ISSUE TITLE
Inconsistent null handling in DimExtractionFn tests

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#1094]
There are a number of unit tests which have DimExtractionFn results which are empty strings instead of null. Example: https://github.com/druid-io/druid/blob/master/processing/src/test/java/io/druid/query/topn/TopNQueryRunnerTest.java#L1779

The specification for DimExtractionFn explicitly states that only null should be returned and never an empty string.

I have a feeling there may be other tests that violate this restriction as well but haven't thoroughly checked.

The options seem to be either update unit tests or remove the null-or-nonempty restriction from DimExtractionFn

**Comment by cheddar** [comment]
@drcrallen Did you read the comment above that test?

**Comment by drcrallen** [comment]
I did now, but it's wrong if I'm reading DimExtractionFn correctly:
https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/query/extraction/DimExtractionFn.java#L54

**Comment by drcrallen** [comment]
This is probably not something that needs fixed immediately, but if more errors start popping up regarding null handling at least there is a trail of evidence for things that need reconciled for a fix.

**Comment by cheddar** [comment]
The comment on the UT says that it is undefined what happens when the empty string is returned.  The docs on DimExtractionFn say that you should not return the empty string and should return null instead.

That seems consistent to me?  The purpose of the test is actually to make it clear when we make a change that will affect what happens when the empty string is returned.  At a minimum we should do something that doesn't bring the server down, for example...
