### ISSUE TITLE
Jackson 2.4.x causing Hadoop dependency problems

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#1356]
Several users have reported problems with Hadoop ingestion once they switched to 0.7.1.1.

**Comment by xvrl** [comment]
It's unclear which version of Jackson would work for everyone. Different distributions probably rely on different version of Jackson, so it might not be possible to find one that works for everyone. As far as I know, stock Hadoop does not depend on com.fasterxml jackson, only the old org.codehaus version, so this seems to be a distribution specific problem.

Instead of downgrading, it might be more useful to provide build profiles for specific versions of hadoop that include the right version of Jackson, similar to what do Apache Spark does.

**Comment by himanshug** [comment]
just a data point, jackson-2.4.x works fine for me with hadoop-2.6

**Comment by xvrl** [comment]
@himanshug are you using stock Apache Hadoop or something else?

**Comment by himanshug** [comment]
@xvrl We have a major hadoop team internally managing a version of hadoop  which is more or less same as apache but might have a few customizations on top.

**Comment by fjy** [comment]
Closing this issue, I think this is only a concern with custom versions of Hadoop
