### ISSUE TITLE
IngestSegmentFirehose may not handle overlapping segments properly

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#1678]
See https://groups.google.com/d/msg/druid-development/ZCXRGzGfXSM/qVVl3W1jDgAJ

It looks like the factory is using a VersionedIntervalTimeline to figure out what segments to read, but doesn't use the interval of the timeline holders to filter the segments.

**Comment by gianm** [comment]
Failing test at: https://github.com/druid-io/druid/compare/master...gianm:ingest-segment-overlapping?expand=1#diff-8b56e359211a285701b559f7bd1296f4R249

**Comment by himanshug** [comment]
looks like this one is going to impact batch delta ingestion as well, because same code is reused there to read data. We probably should put this one as a known bug inside 0.8.1 release notes till fixed.
Also IngestSegmentFirehoseFactory usage of VersionedIntervalTimeline  is looks redundant because IndexerSQLMetadataStorageCoordinator (see https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/metadata/IndexerSQLMetadataStorageCoordinator.java#L75 ) does that as well.

**Comment by gianm** [comment]
This doesn't compile anymore after merging #1609, rebasing back onto master.

**Comment by gianm** [comment]
ok, now it compiles, and that is cool.
