### ISSUE TITLE
[Proposal][QTL] provide reverse lookup mapping via unApply. 

### ISSUE THREAD

**Issue by b-slim** [druid-io/druid#1754]
The goal of this proposal is to introduce an API Change to the interface `LookupExtractor`.

Current interface only exposes `String apply(String input)` that defines a mapping between druid dimension to a mapped value in a given lookup.

In order to support some optimization and/or lookup introspection we can add `List<String> unApply(Sting input)` that provides the reverse mapping from a given lookup value to druid dimensions table.
 One obvious contract of this method is:
for a given input String 
```java
foreach key in unApply(input)
	apply(key) == input
end
```

**Comment by drcrallen** [comment]
The major thing to worry about here is multi-value dimensions, and if you want to support inverting surjective extraction functions.

**Comment by drcrallen** [comment]
Another concern:

An injective extraction function only need be injective for the domain of the dimension of interest in the query of interest. Injective is a query time property because the extraction function may not be injective for an arbitrary domain. As such, any particular extraction function's injective-ness across the set of all possible Strings is not currently a property of a lookup extraction's underlying data map. (it could be added but would require more data about lookups to be propagated around)

Without this change (or other rule enforcement) it is not possible to simply do a full scan of the range of the lookup transformation and guarantee that only the values of interest will return from the function, but since any values outside the dimension should be eventually ignored, this may not be a problem.

To do a full table scan of the dimension values, apply the lookup transformation, and filter on the values is what the dimension extraction filter currently does. The problem is that it cannot be applied in an optimized way (ex: at the broker) because the broker does not know what the potential dimension values are, it only can get the entire domain of the lookup.

Additionally, the lookup fn has the capacity to either retain or replace missing values, including the capacity to treat missing values as null. Such behavior would have to be preserved when doing an unApply.

From prior conversations I'm assuming the point here is trying to make QTL have the capacity to avoid the full dimension-value scan for pattern matching. Doing so should be possible, but it may have to have very specific constraints on when it can be done.

**Comment by cheddar** [comment]
@drcrallen I don't understand.  Can you be more specific?

At a high level, I think that what we are realizing is that the idea of `ExtractionFn` is a good start for QTL, but it's not sufficient.  For this kind of join, we actually need more functionality and I think it makes a lot of sense to enforce that in the interface in order to unify functionality.  You are correct that the big thing we cannot do without `unapply()` is the broker-level rewrites for filters.

**Comment by drcrallen** [comment]
@cheddar Sure,

In the current extractionFn method, the QTL stuff is all represented as a simple map of a set of keys to some values. 

In the current implementation you can have a map as follows:

```
{
  "key1":"value1",
  "key2:"value2",
}
```

Which takes the key# and extracts them to be value#. The most simple case.

The current implementation permits the following functionality:

```
{
  "dim1Key1":"value1",
  "dim1Key2":"value2",
  "dim2Key1":"value1",
  "dim2Key2":"value2"
}
```
For a particular query you may only have dimension values `{"dim1Key1","dim1Key2"}` or `{"dim2Key1","dim2Key2"}` depending on which dimension you are extracting. As such, the individual ExtractionFn which uses the QTL-map can still be injective, since the domain of the dataSource dimension is a subset of the QTL key set. But the total key set for a QTL map (or set of all strings) may not be injective (because there are multiple instances of `value#` in it.

So, if you were to do a simple broker-level rewrite, you could do something like selecting `value1` to mean `dim1Key1 OR dim2Key1`. Which I think would end up being OK because one of the other might never be present.

**Comment by drcrallen** [comment]
@cheddar do you have specific use cases that are not covered well by the simple QTL implementation that currently exists?

**Comment by b-slim** [comment]
@drcrallen Thanks for the comments:
So i am not sure i do understand the concerns about having unApply() at the lookup extractor API.
In fact current implementation of lookup is a map based, Hence it is by construction that the unApply function can be built.
As your example shows it is perfectly fine to filter by `dim1Key1 OR dim2Key1` if the filter value is `value1`. 
Is there a case where unApply can't be constructed ?

**Comment by b-slim** [comment]
@drcrallen any updates about this ?

**Comment by xvrl** [comment]
@b-slim @drcrallen is out today, he should be back tomorrow.

**Comment by b-slim** [comment]
Done
