### ISSUE TITLE
Avro support

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#1844]
Should probably be an extension.

For realtime we need a ByteBufferInputRowParser (something similar to the ProtoBufInputRowParser, but for Avro).

For batch we need a recommended Avro-aware InputFormat and an InputRowParser that can read whatever type is returned by that InputFormat. I haven't used Avro before so I'm not sure what the right choice of InputFormat is. `AvroKeyInputFormat` from https://avro.apache.org/docs/1.7.0/api/java/org/apache/avro/mapreduce/AvroKeyInputFormat.html seems like a possible candidate.

**Comment by himanshug** [comment]
We have had avro working for a while, but code is not generic enough and very specific to our schemas. In fact, it will not be possible to take a general avro schema and convert it to druid row because avro has support for very many complex types, so we will have to compromise anyway. Also, it was written pre druid-0.8.0 era where it wasn't possible to have InputFormats that could return anything but Text records.
With druid-0.8.2, those limitations are gone, it is fairly straightforward to add it as an extension. In my org, some people are [slowly] working on next gen druid avro integration.

**Comment by zhaown** [comment]
I'm using avro with druid for production, for batch indexing, it's not complicated based on @himanshug 's https://github.com/druid-io/druid/pull/1472, and I'm using my `AvroValueInputFormat` which is the mirror of `AvroKeyInputFormat`.

But for realtime indexing, it's a bit more cumbersome because you need an schema to deserialize avro object from binary stream, and you don't want to send schema with every serialized record to kafka. Then you need an schema registry, currently we are using [schemarepo](https://github.com/schema-repo/schema-repo) and `camus schema registry client`, the latter is not in the maven central... 

I'll try to clean my code and try to submit an PR for this this weekend if I got some time.

**Comment by zhaown** [comment]
Please check https://github.com/druid-io/druid/pull/1858
