### ISSUE TITLE
Add a caffeine cache extension

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#2411]
The [caffeine](https://github.com/ben-manes/caffeine) library is an interesting caching library that shows great promise in highly performant caching.

There are a few cache layers which have been proposed recently, namely

* https://github.com/druid-io/druid/pull/1849 Guava based caching
* https://github.com/druid-io/druid/pull/2351 Guava based caching
* https://github.com/druid-io/druid/pull/1937 Redis based caching
* https://github.com/druid-io/druid/pull/1800 L1/L2 caching

This ask is to add an extension so that Caffeine (similar to #1937 Redis extension) can be included as a caching layer.

A few notable concerns:

* http://mvnrepository.com/artifact/com.github.ben-manes.caffeine/caffeine/2.1.0 testing dependencies require guava 19. And Druid requires guava 16 in order to retain hadoop compatibility. This would need to be tested to make sure guava 16 is still OK.
* Caffeine requires java8.

**Comment by ben-manes** [comment]
It is atypical to include an external project's tests and test dependencies, so that shouldn't be an issue.

It sounds like the Guava performance wasn't robust enough to be used as the default. If it was, then Caffeine's Guava adapters would an easy bridge and are most likely Guava v16 compatible.

For Java 7, it does appear that @binlijin was correct and [CLHM](https://github.com/ben-manes/concurrentlinkedhashmap) could be a drop-in replacement for the synchronized map. It introduced the idea of a `Weigher`, then brought over into Guava, to handle the byte sizing issue. It is currently used by Cassandra, et. al, and provides concurrent throughput close to Caffeine. It would be a reasonable stop-gap, with Caffeine preferred in Java 8 due to its superior hit rate.

**Comment by drcrallen** [comment]
FYi, there was a brief [discussion](https://groups.google.com/d/msg/druid-development/6I9uhO3ZIeQ/WG-K6JdEEQAJ) on how long we should support java7, which didn't end up in any official position (the discussion is still open).
