### ISSUE TITLE
distribution tarball should be created as part of maven package phase

### ISSUE THREAD

**Issue by xvrl** [druid-io/druid#2440]
With #1638, the assembly tarball was changed to be created as part of the install phase, whereas previous Druid versions used to create it as part of the package phase.

This means that running `mvn release:prepare` alone is no longer enough to generate the tarball, which was useful to upload release candidate builds, which we do not publish to maven central

**Comment by xvrl** [comment]
@guobingkun would you mind looking into this?

**Comment by guobingkun** [comment]
The main reason that we have to use ```mvn install``` to get the tarball is because we've changed the layout of extension files in the tarball, in order to get extensions files we have to call ```pull-deps``` in the end of the build, which requires extension jars installed in the local repository.

The pain point comes from the fact that releasing RCs becomes very convoluted. In order to get the tarball, you have to manually change pom tags and then do ```mvn install```.

A simple hack is let ```mvn package``` install the jars in the local repository so that we can get the tarball by ```mvn package```.
