### ISSUE TITLE
DumpSegment tool

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#2723]
It'd be nice to have a dump-segment tool that you could invoke like:

```
io.druid.cli.Main tools dump-segment segment1 [segment2 segment3...]
```

This would point directly at a segment directory and should dump all rows in the segment as, I dunno, JSON maybe? Would probably do something like:

- __time as ISO8601
- dims as null, string, or array of strings
- numeric metrics as numbers
- complex metrics as base64 encoded versions of the raw bytes? I guess? could be worth special-casing this so folks can dump something more useful. Like for HLL it'd be good to see the header and buckets encoded in some friendly way.

**Comment by gianm** [comment]
The use case for this tool would be running it on a historical node, or indexing node, or on a segment you downloaded yourself from deep storage.

**Comment by drcrallen** [comment]
Is the point here to be able to copy the data, or just to get insight into what's going on in the segment?

If the point is to copy the data, then I could see a base64 encoding of complex metrics working well to solve that use case,

but if the point is to get insight into the segment, then for complex metrics perhaps a toString call or similar so that the complex metric can decide for itself what is important.

**Comment by gianm** [comment]
@drcrallen hmm, good question. The use case I had in mind was "to get insight". it may make sense to have a flag to switch behavior, so the "copy data" folks can have something that works for them.

**Comment by drcrallen** [comment]
I propose having the scope here be limited to the "gain insight" use case and have any copy-data needs be addressed through the DatasourceInputFormat (or similar) functionality.

**Comment by gianm** [comment]
that sounds fair.
