### ISSUE TITLE
S3 Lookups might be doing full GET requests to S3 instead of just looking at metadata

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#2894]
As per https://github.com/druid-io/druid/issues/2523#issuecomment-215495808 lookups regularly call `org.jets3t.service.S3Service#listObjects` when checking for new values.

This needs to be investigated to see if it can only check metadata and does not issue a full GET call.

**Comment by pdeva** [comment]
it seems i am running into this issue too:
https://groups.google.com/forum/#!topic/druid-user/RUc8BNQ_6Ys

**Comment by gianm** [comment]
@drcrallen `URIExtractionNamespaceFunctionFactory`'s cache popular calls `puller.getVersion(uri)` on the uri returned from `getLatestVersion`. `puller.getVersion` does a full `getObject` (does a GET). It doesn't need to do that, it could get away with `getObjectDetails` (does a HEAD).

Even a `getObjectDetails` doesn't seem necessary, since the objects that come back from `listObjects` have the modified dates in them.

**Comment by drcrallen** [comment]
@gianm thanks, I'll see if I can get it updated with that fix for 0.9.1
