### ISSUE TITLE
DataSchema.equals does not account for different parse specs meaning the same thing

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#2914]
`io.druid.segment.indexing.DataSchema#equals` calls `parser.equals(that.parser)` which assumes the parse spec map representation is unique per "equal" parse spec impl.

With legacy dimension specs which were only strings, this was the case, but with the changes in https://github.com/druid-io/druid-api/pull/75 the map portion which is the parse spec dimension specification can be represented as an array of strings (legacy) or an array of maps.

**Comment by drcrallen** [comment]
@jon-wei fyi

**Comment by fjy** [comment]
@drcrallen this is really needed in 0.9.1?

**Comment by xvrl** [comment]
@fjy it broke one of our unit tests in spark batch indexing, so yes

**Comment by gianm** [comment]
Since 74f4572bd49a04b4ca381fcd7b8f360c8ef52480 I don't think it's possible to have a semantic equals/hashCode impl for DataSchema that avoids creating the parser (which seems like a good thing to avoid… it'd be weird if equals/hashCode triggered that). Two semantically equivalent parsers could be made from two different maps. (even before druid-io/druid-api#75 this could happen because e.g. `dimensionExclusions: []` and `dimensionExclusions: null` do the same thing)

Since it's not possible to get these methods right, I think we should remove them (verifying we don't need them in production code) and have the tests be a little more verbose.

**Comment by gianm** [comment]
Looking through production usages I don't see anything that would rely on equals/hashCode being semantic, so I think they're safe to remove. (could use a doublecheck on that though)

**Comment by xvrl** [comment]
@gianm we still need a way to test DataSchema serde

**Comment by gianm** [comment]
Test the fields for equality individually? There's only 4, the test wouldn't be *THAT* verbose. That's probably more honest than implementing an equals method that doesn't (and really, can't) work properly.

**Comment by xvrl** [comment]
@gianm maybe a better solution is to remove the parser field from the data schema, since the parser just defines how to read the data, but has nothing to do with the actual schema

**Comment by gianm** [comment]
It unfortunately does have to do with the schema, because the parser defines both the data format and the dimensions for the schema. IMO that is a bit weird though, it should probably only define the format.

Unrelated to that, it's also weird that inside the parser, the ParseSpec sometimes defines the data format (if you're using the string input row parser) but sometimes doesn't (if you're using any other input row parser).

Anyway, I do think both of those are weird and we could do a better API, but that is how it works right now, and changing either would be backwards incompatible…

**Comment by jon-wei** [comment]
What do you all think about this approach for making equals() work?

https://github.com/druid-io/druid/pull/2927

**Comment by drcrallen** [comment]
It came up in the dev-sync, but the origination of the separation comes from https://github.com/druid-io/druid/pull/1695
