### ISSUE TITLE
Race condition in IncrementalIndex's facts

### ISSUE THREAD

**Issue by KurtYoung** [druid-io/druid#2991]
In OnheapIncrementalIndex::addToFacts(...), when we get a new fact, we will first add the mapping from key to fact's index, then we do aggregate. It will cause query saw some unaggregated metrics with initial value, and sometimes may cause some weird situations. Like if we use LongMax for build but use LongSum for query, then the result may add LongMax's initial value which is LONG.MIN_VALUE.

BTW, do we need to deal with this:
```
      final Integer prev = facts.putIfAbsent(key, rowIndex);
      if (null == prev) {
        numEntries.incrementAndGet();
      } else {
        // We lost a race
        aggs = concurrentGet(prev);
        // Free up the misfire
        concurrentRemove(rowIndex);
        // This is expected to occur ~80% of the time in the worst scenarios
      }
```
I don't find any multi-thread adds for IncremetalIndex.

**Comment by gianm** [comment]
Multi-threaded add in IncrementalIndex exists because it is also used for groupBy, which does multi-threaded merging of partial results. In #2987 I'm suggesting no longer using IncrementalIndex for groupBy, which could mean IncrementalIndex might not have to support multi-threaded adds anymore.

Btw, out of curiosity why would you use longMax for building but longSum for querying?

**Comment by KurtYoung** [comment]
@gianm It's a *hack* solution for one of our realtime cases. We use druid to consume a streaming job's output to calculate some metrics like PV which is obviously sum(each_pv). But it's difficult to let the streaming job output each record exactly once because failover always exists. So we add a primary key to the event and make it dimension. Now we can use LongMax to dedup the duplicated events, and use LongSum to query.
