### ISSUE TITLE
[Proposal] QTL Optimization by doing bulk Lookup

### ISSUE THREAD

**Issue by b-slim** [druid-io/druid#3030]
The goal here is to make sure that most of the lookup operation are executed by bulk using the method `applyAll(iterable<T> keys)`. Generally point lookup can be very expensive and doing it by bulk will speed up the query. For instance in case of your lookup table is accessible via a JDBC, you might want to avoid doing `SELECT key, value FROM table WHERE key LIKE myKey` and do `SELECT key, value FROM table WHERE key IN [keys]`.
This optimization need to be done in several places.
1. First (most obvious) when your lookup will not affect the aggregation where the mapping is ONE to ONE ( called injective) this can be done while merging the results at the broker level. One can walk through the sequence, gather the keys, do a bulk lookup in order to build a lookup map locally, then build a new sequence out of the old sequence using the lookup map. 
2. Second (less obvious), for the case where lookup can affect aggregation (not injective), this optimization can be done at the QueryEngine it self.

**Comment by gianm** [comment]
Re 1: "walk through the sequence, gather the keys, do a bulk lookup in order to build a lookup map locally, then build a new sequence out of the old sequence using the lookup map" will require either materializing the sequence or computing it twice (two sets of queries to data nodes). Materializing will negate the broker's ability to stream back results so I think we should avoid that. Better approach might be to materialize the sequence in batches (like 1000 or 10000 rows at a time) and then do bulk lookups for keys in each batch.

**Comment by b-slim** [comment]
@gianm totally make sense.

**Comment by gianm** [comment]
@b-slim are you still planning to drive this? Shall we move to 0.10.1?

**Comment by b-slim** [comment]
This has a low priority right now.
