### ISSUE TITLE
Wires crossed on lookup caching

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#3031]
A couple of folks in this thread had issues with wires getting crossed when they have two lookups in the same directory. I'm not sure if this still applies in master with the recent QTL changes.

https://groups.google.com/d/topic/imply-user-group/H-RgHyFZzVM/discussion

**Comment by gianm** [comment]
I _think_ #2738 fixed this.

**Comment by drcrallen** [comment]
I believe you are correct. The original intention was to always have a pattern matching for the lookup specification, as such the uri base specified had things after the final '/' pretty much not treated how the user expected. The addition in #2738 was to account for the common case of exact file names rather than pattern matching.

**Comment by gianm** [comment]
@drcrallen, thanks for confirming.
