### ISSUE TITLE
Only one class loader is created for multiple hadoopDependencyCoordinates

### ISSUE THREAD

**Issue by jon-wei** [druid-io/druid#3163]
If I post an indexing task with hadoop coordinates like:

```
  "hadoopDependencyCoordinates": ["org.apache.hadoop:hadoop-client:2.7.1", "org.apache.hadoop:hadoop-aws:2.7.1"]
```

the function Initialization.getClassLoaderForExtension does not create a class loader for the second dependency in the list.

```
  public static URLClassLoader getClassLoaderForExtension(File extension) throws MalformedURLException
  {
    URLClassLoader loader = loadersMap.get(extension.getName());
...
```

This occurs because the two dependencies have the same "extension name", the hadoop version:

FILE: /Users/jw/jw_repo/druid/hadoop-dependencies-tmp/hadoop-client/2.7.1
EXTNAME: 2.7.1

FILE: /Users/jw/jw_repo/druid/hadoop-dependencies-tmp/hadoop-aws/2.7.1
EXTNAME: 2.7.1

**Comment by drcrallen** [comment]
The hadoop dependency stuff should be loaded at https://github.com/druid-io/druid/blob/druid-0.9.1-rc4/indexing-service/src/main/java/io/druid/indexing/common/task/HadoopTask.java#L151

Ah, I see now, The loader map at https://github.com/druid-io/druid/blob/druid-0.9.1-rc4/server/src/main/java/io/druid/initialization/Initialization.java#L87 should probably be File based rather than String based for the key.
