### ISSUE TITLE
Slow segment loading from S3

### ISSUE THREAD

**Issue by Dunedan** [druid-io/druid#3202]
We noticed that segment loading from S3 on historical nodes running Druid 0.9.0 is way slower than expected. While our hardware should be capable of loading more than 400MB/s, we only see around 42MB/s on average.

While digging into that we noticed that even though we set `druid.segmentCache.numLoadingThreads=25` only one of the loading threads is active at a time, as shown in the following picture:
![visualvm-sequential-segment-loading-threads](https://cloud.githubusercontent.com/assets/1735355/16443386/c1a0536a-3dd8-11e6-98e1-8e2069358166.png)

This leads to sequential loading of segments instead of parallel loading as one would expect it when using multiple threads.

We think this could be a bug in how Druid handles the segment loading from S3 (or possibly from deep storage in general).

Some additional information including a log file showing the sequential loading as well is available in the following thread on the mailinglist: https://groups.google.com/forum/#!topic/druid-user/doaE61OLHEo

**Comment by drcrallen** [comment]
General note that `numLoadingThreads` and `numBootstrapThreads` do two different things. 

It looks like `numLoadingThreads` is not handled properly. That config is used to create the executor for the PathChildrenCache, which explicitly states: `ExecutorService to use for the PathChildrenCache's background thread. This service should be single threaded, otherwise the cache may see inconsistent results.`

**Comment by l15k4** [comment]
Hi, regarding segment loading performance, should this `druid.segmentCache.announceIntervalMillis` be set to zero when adding a new historical node? For the segments to be loaded faster?
