### ISSUE TITLE
Increment version before handoff to historicals

### ISSUE THREAD

**Issue by niketh** [druid-io/druid#3589]
It would be nice to have the version number incremented before the realtime node hands off the segment to the historical. This ensures that the queries are only routed to the historicals in case the 2nd realtime process zombies.

We plan to add a string "_handoff" at the end of the version number so that the new version is higher on the historicals as compared to realtime zombie node

**Comment by b-slim** [comment]
i guess trying to solve the issue that one realtime node is in a non  responsive state, but this suggestion will only work if the handoff did occur, what about other cases ? i don't think it is a valid fix.

**Comment by cheddar** [comment]
It wouldn't benefit the case where the handoff doesn't actually succeed, that's true.  In that case, we would still get non-deterministic results based on which realtime task the broker chooses to send the query to.

In the current world, that status continues through even after handoff has succeeded, this suggested change would make that state end as soon as handoff completes successfully.

**Comment by gianm** [comment]
Won't this mess up situations where there are multiple partitions? Adding `_handoff` to the version number of the first to handoff will mean it all of a sudden forms a singleton shard set and overshadows the other partitions served from realtime.

**Comment by gianm** [comment]
Assuming you're using the "expandable" shard sets that are popular with realtime, since they are considered complete even with just a single partition.

**Comment by cheddar** [comment]
I haven't double checked the code recently, but I thought hand-off looked for the partition that it handed off or something greater.  Thinking about it, I guess the logic might be that "if it sees a complete partition set with a greater version, then assume handoff succeeded", in which case you are correct, @gianm 

If that's the logic, then I think it should be possible to make the handoff intelligent enough to look for the `_handoff` version instead of the version that it is looking for today.  In that case, it should be exactly equivalent to the handoff logic today, just the broker-published segment will have the non `_handoff` version, no?

**Comment by gianm** [comment]
Ha, @cheddar, I wasn't even thinking about that problem you're thinking about. I was thinking of a different thing:

1. v1_0 and v1_1 exist in rt
2. v1_handoff_0 shows up on historicals
3. now the broker things "oh, wow, v1_handoff is way better than v1, I should use that set" – and v1_1 stops showing up in queries.

Anyway, for the original problem statement, rather than mucking with versions I think it would be way simpler to have the broker prefer non-realtime versions of a segment if they exist. It already knows about realtime vs non-realtime servers for caching reasons, so it has the info it needs to do that.

**Comment by cheddar** [comment]
Ok, I buy that.
