### ISSUE TITLE
Issue with segment after 0.10.0-rc1 upgrade 

### ISSUE THREAD

**Issue by naman-aasaan** [druid-io/druid#4021]
After upgrading to 0.10.0-rc1from 0.9.2 we are facing issues with respect to segment not getting loaded on HDFS properly.

We can see below exceptions in ladka indexing jobs -

org.apache.hadoop.fs.FileAlreadyExistsException:  rename destination

We are using hadoop 2.7.3.

We can see below in coordinator logs 
skipping doNext () because something is currently loading 

Did we miss anything in configuration or there is something wrong with the latest version ?

**Comment by niketh** [comment]
@naman-aasaan It is expected to have  `org.apache.hadoop.fs.FileAlreadyExistsException` when you have 2 replicants for realtime. Your tasks shouldn't fail because of this, do you see your tasks failing?

**Comment by gianm** [comment]
@naman-aasaan You might be hitting #3997 which was a bug in rc1 when you have more than one segment for the same interval. If so then this will be fixed in rc2 which should be out soon.

**Comment by naman-aasaan** [comment]
Ok. As I visited referenced issue, it is already closed and reference issue given in 3997 also has been closed. So if I build using latest master. Will this resolve my problem for now.

**Comment by gianm** [comment]
@naman-aasaan yes it should. Or, you could build with the latest 0.10.0 branch, which is our release branch and also includes the fix.

**Comment by naman-aasaan** [comment]
OK. That will really Help, Thanks @gianm.

**Comment by knepperjm** [comment]
Guys, I'm having this issue too:

`9/1/2017 5:16:03 PM2017-09-02T00:16:03,634 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/1/2017 5:16:03 PM2017-09-02T00:16:03,684 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/1/2017 5:16:03 PM2017-09-02T00:16:03,734 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/1/2017 5:16:03 PM2017-09-02T00:16:03,784 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/1/2017 5:16:03 PM2017-09-02T00:16:03,834 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/1/2017 5:16:03 PM2017-09-02T00:16:03,885 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/1/2017 5:16:03 PM2017-09-02T00:16:03,935 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/1/2017 5:16:03 PM2017-09-02T00:16:03,985 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/1/2017 5:16:04 PM2017-09-02T00:16:04,035 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/1/2017 5:16:04 PM2017-09-02T00:16:04,085 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/1/2017 5:16:04 PM2017-09-02T00:16:04,136 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/1/2017 5:16:04 PM2017-09-02T00:16:04,186 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/1/2017 5:16:04 PM2017-09-02T00:16:04,236 INFO [Master-PeonExec--0] io.druid.server.coordinator.LoadQueuePeon - Server[/druid/loadQueue/10.42.246.38:8083] skipping doNext() because something is currently loading[ip_queries_daily_v4_2017-08-30T00:00:00.000Z_2017-08-31T00:00:00.000Z_2017-08-31T21:02:34.723Z_20].
9/`

I am on v0.10.1-rc3.

**Comment by gianm** [comment]
@knepperjm, are you just seeing the excessive logging of "skipping doNext" messages or are you seeing some other issue? The excessive logging is "harmless" (other than being annoying) and is fixed for the next release by #4680.
