### ISSUE TITLE
Make Caffeine the default in-memory cache

### ISSUE THREAD

**Issue by ben-manes** [druid-io/druid#4067]
Per #4062, Druid now requires a Java 8 runtime. Previously the JDK7 support meant that the Caffeine integration was provided as an optional plugin. The default in-memory cache is a synchronized LinkedHashMap, which has low performance in production usages.

Switching was [approved](https://github.com/druid-io/druid/pull/4062#issuecomment-286888958) so this should improve the out-of-the-box experience.

**Comment by gianm** [comment]
@ben-manes would you be willing to contribute a patch that does the necessary shuffling around of things?

**Comment by ben-manes** [comment]
I could try, but I wouldn't be able to get to it for a week or two.

**Comment by gianm** [comment]
You might still get to it first!

Going to mark this 0.10.1 since it seems like something we should be able to do for the next release.

Btw, there is no "default" cache (by default cache is disabled, and enabling it requires setting a specific cache type) so imo, what this issue should be about is:

- Move caffeine-cache from an extension to core
- Update the example cache configs (where most users get their first cache configs from) to use `caffeine` instead of `local`
- Update other caching related docs, and release notes, to push people towards choosing `caffeine` over `local`
- Possibly deprecate `local`

An alternative interpretation is we should merge `local` with `caffeine` so they both do the same thing, but I don't think we should do this right now, in part because the configs are different and so it wouldn't be a fully compatible change with folks' existing configs. imo, it would make sense to do that in the next major release when `local` is not just deprecated, but removed.

**Comment by drcrallen** [comment]
To play Devils' advocate here:

Is there any advantage to moving it to core vs updating the example configs to include it by default?

**Comment by gianm** [comment]
My thinking is that since local and memcache are not-extensions, having caffeine be an extension makes it feel less "recommended". If local cache and memcache became extensions too then it would make sense for caffeine to stay an extension.

**Comment by drcrallen** [comment]
Would moving memcached and local to extensions make sense?

**Comment by drcrallen** [comment]
Or maybe just memcached

**Comment by drcrallen** [comment]
A "reference implementation" with no external dependencies is a good thing to keep in core druid

**Comment by drcrallen** [comment]
Having quality extensions helps serve as examples and templates for new developers.

**Comment by gianm** [comment]
Are you envisioning a path to deprecating and eventually removing `local` in that case? I was thinking a process like (1) move caffeine to core, (2) deprecate local, (3) remove local, (4) now caffeine is the only remaining local mode cache.

If caffeine stays an extension that at steps (3) and (4) we won't have any cache impl in core.

**Comment by drcrallen** [comment]
I was thinking:

1. Make things that are extension point AND require external dependencies be an extension
2. Move memcached to an extension
3. Make "local" the reference implementation inside of Druid and memcached/caffeine the reference extensions in extensions-core.
4. Since the hybrid cache doesn't require external dependencies, I'm not quite sure where it would fall here.

I'm not convinced this is the right way to go, this is just the first time we've had an extension that is hands down superior to the things that have been packaged in druid before. So spending some time figuring out what should be a core-extension vs what should be packaged in druid default makes some sense.

Core extensions are already packaged in every release, and cache is disabled by default, so since people have to choose the cache impl anyways and modify configs, I don't think it is undue burden.

**Comment by drcrallen** [comment]
so by "make default" if this means "use in all the examples and highly recommend it" then that can (and should) be done in either scenario.

**Comment by gianm** [comment]
I don't see a purpose of keeping `local` around if `caffeine` is just straight up better. `caffeine` can still serve as a reference implementation, even though it delegates to another library it still does a good job of demonstrating how to write a Druid cache implementation.

**Comment by ben-manes** [comment]
Retaining `local` becomes the easiest (preferred) solution for users looking to quickly solve a performance problem. You might later want to enable it by default if you want a good out-of-the-box experience. I'd argue for removal of `local` because there seems to be no benefit, there is more code to maintain, and it might confuse users.

I have no opinion on whether it should be replaced by Caffeine going into core or all caches becoming extensions. I'd only advise to favor towards a new user's experience where they will make minimal changes to your distribution's configuration.

**Comment by himanshug** [comment]
so there are 3 things and my thoughts are below ...
(1) what should be default cache when user does not specify anything in the properties? Ans: caffeine cache, and everyone agrees on this
(2) when user says `local` in the properties, what implementation should be used? Ans: caffeine cache impl given that it is a drop-in much better replacement of MapCache.
(3) should we or should we not keep caffeine impl in an extension? Ans: We should keep it in the extension where it also serves as good reference. Have concept of "enforced extensions in loadList" in Druid and always include caffeine extension in the loadList in addtion to user's supplied loadList . I think this model also gives us flexibility to have more things that can be done in extension but still available to user without any extra configuration.

**Comment by gianm** [comment]
For (1) do you mean "if the user uses the default configs from the distribution"? Since right now, if a user really specifies no cache properties (deleting the ones that come by default in the distribution) then they will get no caching at all. Or did you just mean we should update the default configs to switch from local to caffeine? (PS I also think we should switch the cache from running broker-side, to running historical-side, since it scales better)

For (2) I think it's good to have `local` really mean caffeine, and delete the existing local impl; that will really help people that have `local` cache set and don't read release notes to realize they should switch.

For (3) "enforced extensions" seems weird, but I could propose an even weirder (but also maybe cooler?) thing: some code in core Druid that knows that if `druid.cache.type=local` is set, then it has to load the caffeine extension, and it would just add it to your loadList dynamically. It may look like a hack at first but it is kind of neat: it means that if someone uses memcached (or disables caching entirely) then the caffeine extension won't need to be loaded.

**Comment by himanshug** [comment]
For (1) i meant if they enable caching but don't set cache type , then caffeine cache should be used.

For (3) I was imagining "enforced extensions" a more general thing than used in this context and use same thing whenever we wanted to do things in extensions but still make them available to user without explicitly specifying in loadList. Is there any problem to have caffeine cache extension always being loaded ? it would be same even if we moved it to druid-core .
Dynamic loading is more magical and less general. That said, given that this is all internal to Druid code and is not visible to user, I don't have too strong an opinion here since it can be changed anytime we want with no impact to user.

**Comment by jon-wei** [comment]
For (1), I agree with using "caffeine" as the default if caching is enabled on broker/historical but no type has been specified.

For (2), since the configuration is different for "local" vs. "caffeine", I think we should just drop the "local" type completely instead of having a transition period where "local" means the same thing as "caffeine" (since the user would have to update to a different configuration format anyway if we switched the implementations internally).

For (3) I don't have a strong opinion; having default behavior rely on an extension feels a little weird to me, if something will always be loaded I feel like it should be in core, but as others have pointed out it could be useful as a reference. 

------

So in terms of a sequence of steps I'm thinking:
1. Update all docs and examples to use "caffeine" as default instead of "local", strongly indicate in the docs that "local" is totally inferior to Caffeine and will be deprecated->removed.
2. Decide after that whether to keep the cache implementations in core or as extensions
3. Remove "local" implementation completely in a later release

-----

For 0.10.1 release, since it looks like it might take some time to reach consensus on all aspects of this issue, should we just update the docs/examples to use Caffeine as default and recommend that users switch from "local"?

**Comment by ben-manes** [comment]
Huzzah!
