### ISSUE TITLE
Druid kafka indexing service task consumer lag

### ISSUE THREAD

**Issue by Nachiket90** [druid-io/druid#4101]
Hi,

Is there any way to get lag in number of messages between kafka topic producer and druid kafka indexing service task consumer? I see in indexing service code that offsets are not committed to kafka because of task replication and event/message processing. Currently lag metrics are not available as part of druid metrics. Is there any way to get them in terms of JMX metrics or graphite metrics?

**Comment by pjain1** [comment]
I don't think there is any metric like that however I think it might be useful to add that. One indirect way is to monitor lag would be to use this metric if you have a realtime pipeline - 
```
ingest/events/messageGap - Time gap between the data time in event and current system time.
```

**Comment by gianm** [comment]
You can get the current Kafka offsets that Druid is consuming at using the "Get Supervisor Status Report" API mentioned at http://druid.io/docs/latest/development/extensions-core/kafka-ingestion.html. If you subtract that from the latest offsets in Kafka, you'll get the lag.

It'd definitely be nice for Druid to do that itself, although I believe it currently doesn't.

**Comment by Nachiket90** [comment]
Thanks @gianm  and @pjain1 for suggestions. Currently I am using way suggested by @gianm but it looks messy and I need to write additional code to send those metrics to graphite or influx. Can you point me direction in druid source where I can add this as part of ingest metrics? I'll give it a try.

**Comment by gianm** [comment]
If you check out KafkaSupervisor you should be able to find the code that does the status reports. Search for `"currentOffsets"` in the code (one of the keys in the report) to find it.

I think when adding lag, you're going to need to retrieve the latest offsets as well from Kafka, and the most important thing to do there is make sure that this call happens in a way that doesn't block anything else important. Since it's a network call and it might take a while.

**Comment by knoguchi** [comment]
I just [talked about the same issue](https://groups.google.com/forum/#!topic/druid-user/sNOyoXR5WDE) in the users ML.  One option I thought of is to let KafkaSupervisor report the offsets to the brokers by `commitSync(Map<TopicPartition,OffsetAndMetadata> offsets)` so that readily available monitoring tools would work.   The offset in the broker is for the monitoring purpose only.  The supervisor should never read them out.
