### ISSUE TITLE
Some Kafka-related unit tests take too long time

### ISSUE THREAD

**Issue by jihoonson** [druid-io/druid#4247]
With my laptop, the testing for ```druid-kafka-indexing-service``` took 10:30 min while the total testing time was 24:53 min. Especially, ```KafkaSupervisorTest``` and ```KafkaIndexTask``` contribute a lot to the testing time which were 202.446 sec and 627.351 sec, respectively.

**Comment by gianm** [comment]
I think a lot of this is because real Kafka brokers are getting setup and torn down with each test. I like that they're real instead of mocks (helps this be like a mini-integration-test) but we could reuse them. Maybe a different topic for each test, that way we don't need to tear down and recreate the whole broker.

**Comment by jihoonson** [comment]
@gianm, thanks. I'm working on this.
