### ISSUE TITLE
Update Jackson to >= 2.6

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#4372]
There are numerous problems with sticking to Jackson < 2.6, including lacking spark compatibility and lacking compatibility with recent versions of various cloud SDKs.

This ask is that Jackson be upgraded.

**Comment by gianm** [comment]
Can you add some color about why Jackson has not yet been upgraded and what makes it difficult?

**Comment by leventov** [comment]
Hadoop will _always_ have the most stale dependencies, due to it's development "velocity". Always having Druid to stay on as old library versions as Hadoop use (and not the newest Hadoop!) is very sad. Is it approachable to decouple Hadoop and have a separate set of dependencies for it? For example Jackson sends JSON after all, so on protocol level there should be no difference between any Jackson version.

**Comment by gianm** [comment]
Newer hadoop versions have some better classloader control, it's possible we could find a set of parameters that allows us to update jackson, and tell users to use those parameters. I'm not totally sure if this will work though.

**Comment by drcrallen** [comment]
@gianm https://github.com/druid-io/druid/pull/1674

**Comment by drcrallen** [comment]
A profile `-P spark2` was added in https://github.com/druid-io/druid/pull/4808
