### ISSUE TITLE
CacheDistributionTest is not a test

### ISSUE THREAD

**Issue by jihoonson** [druid-io/druid#4465]
This class is not a test, but takes long time in our travis (https://github.com/druid-io/druid/issues/4402#issuecomment-309642796).

**Comment by jihoonson** [comment]
I'm not sure what the best way is. If this test is deterministic, the best is making it as a valid test class and reducing testing time. If not, we can make this class not running on travis or changing it from a test class to something another like benchmark class.

@xvrl do you have any idea on this?

**Comment by xvrl** [comment]
@jihoonson completely agree this is not a unit test, since it doesn't verify anything. It is just a qualitative test you would want to run if we decided to change the hash function used in the cache. The reason it was created in the first place was that the initial hash function used for cache keys was not very uniformly distributed, causing very uneven cache load across cache nodes.

**Comment by xvrl** [comment]
We should probably just mark the test as `@Ignore` and add a comment to the cache code to remind us to verify even key distribution using this test in the event that someone decides to use a new hash function.

**Comment by jihoonson** [comment]
@xvrl thanks. I raised #4527.
