### ISSUE TITLE
QTL problem during upgrade to 0.10.x

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#4603]
During the course of upgrading, there is a time where historicals and the coordinator will be on different versions. When the historicals are updated to the latest version, they like to spew the following error:

```
got notice to load lookup [LookupExtractorFactoryContainer{version='null', lookupExtractorFactory=io.druid.query.lookup.NamespaceLookupExtractorFactory@*}] that can't replace existing [LookupExtractorFactoryContainer{version='null', lookupExtractorFactory=io.druid.query.lookup.NamespaceLookupExtractorFactory@*
```

**Comment by drcrallen** [comment]
This *might* just be noise during the switchover, but is very annoying

**Comment by gianm** [comment]
@himanshug do you know if this is expected or not?

**Comment by himanshug** [comment]
@drcrallen @gianm it is expected. The reason is that when historical is on 0.10.1 while coordinator is on smaller version, coordinator would try to propagate lookups to historical even if they are already loaded on the historical... historical prints a warning on receiving request to load a lookup whose same or higher version is already loaded.
warning message is intended to find out any bugs in coordinator code, 0.10.1 coordinator is suppose to first check with historical what it has and then ask it to do stuff so these warnings shouldn't get printed once coordinator is upgraded too.

**Comment by drcrallen** [comment]
The concern is that it reports as an error but isn't really an error, which makes it harder to catch real errors. I propose simply calling it out in the release notes.

**Comment by drcrallen** [comment]
Resolving by adding info to release notes

**Comment by himanshug** [comment]
@drcrallen  I believe the message to be printed from https://github.com/druid-io/druid/blob/0.10.1/processing/src/main/java/io/druid/query/lookup/LookupReferencesManager.java#L366 which is a "warn" not "error" . Did you see "error" printed ? that would be unexpected.
in any case, i think its great to put it in release notes to avoid surprises. @drcrallen @jon-wei thanks.
