### ISSUE TITLE
/druid/coordinator/v1/datasources authorization error

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#4860]
Some other APIs use the same helper methods and may be affected too.

Error log:

```
2017-09-26T20:20:18,740 WARN [qtp1115349385-90] org.eclipse.jetty.server.HttpChannel - //localhost:8081/druid/coordinator/v1/datasources
io.druid.java.util.common.ISE: Request did not have an authorization check performed.
        at io.druid.server.security.PreResponseAuthorizationCheckFilter.handleAuthorizationCheckError(PreResponseAuthorizationCheckFilter.java:156) ~[druid-server-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSH
OT]
        at io.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:91) ~[druid-server-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[jetty-servlet-9.3.19.v20170502.jar:9.3.19.v20170502]
        at io.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:83) ~[druid-server-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
        at io.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:60) ~[druid-server-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[jetty-servlet-9.3.19.v20170502.jar:9.3.19.v20170502]
        at io.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:86) ~[druid-server-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[jetty-servlet-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) ~[jetty-servlet-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) ~[jetty-servlet-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:493) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.server.Server.handle(Server.java:534) ~[jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [jetty-io-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [jetty-io-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by aceteam-dfs** [comment]
Getting the same error, pulled the latest from master:

2018-04-04T15:06:35,864 ERROR [qtp1825811850-78] io.druid.server.security.PreResponseAuthorizationCheckFilter - Request did not have an authorization check performed.: {class=io.druid.server.security.PreResponseAuthorizationCheckFilter, uri=/console.html, method=GET, remoteAddr=172.18.0.1, remoteHost=172.18.0.1}
docker-druid       | 2018-04-04T15:06:35,941 WARN [qtp1825811850-78] org.eclipse.jetty.server.HttpChannel - //localhost:8081/console.html
docker-druid       | io.druid.java.util.common.ISE: Request did not have an authorization check performed.
docker-druid       | 	at io.druid.server.security.PreResponseAuthorizationCheckFilter.handleAuthorizationCheckError(PreResponseAuthorizationCheckFilter.java:158) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:91) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:85) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:60) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:86) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:493) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.Server.handle(Server.java:534) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
docker-druid       | 2018-04-04T15:06:53,224 ERROR [qtp1825811850-97] io.druid.server.security.PreResponseAuthorizationCheckFilter - Request did not have an authorization check performed.: {class=io.druid.server.security.PreResponseAuthorizationCheckFilter, uri=/, method=GET, remoteAddr=172.18.0.1, remoteHost=172.18.0.1}
docker-druid       | 2018-04-04T15:06:53,680 WARN [qtp1825811850-97] org.eclipse.jetty.server.HttpChannel - //localhost:8081/
docker-druid       | io.druid.java.util.common.ISE: Request did not have an authorization check performed.
docker-druid       | 	at io.druid.server.security.PreResponseAuthorizationCheckFilter.handleAuthorizationCheckError(PreResponseAuthorizationCheckFilter.java:158) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:91) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:85) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:60) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at io.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:86) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:493) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.Server.handle(Server.java:534) ~[druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [druid-services-master-selfcontained.jar:master]
docker-druid       | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
docker-druid       | 2018-04-04T15:07:20,715 INFO [LookupCoordinatorManager--2] io.druid.server.lookup.cache.LookupCoordinatorManager - Not updating lookups because no data exists
docker-druid       | 2018-04-04T15:07:27,872 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Starting coordination. Getting available segments.
docker-druid       | 2018-04-04T15:07:28,520 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Found [0] available segments.
docker-druid       | 2018-04-04T15:07:28,942 INFO [Coordinator-Exec--0] io.druid.server.coordinator.ReplicationThrottler - [_default_tier]: Replicant create queue is empty.
docker-druid       | 2018-04-04T15:07:29,124 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorCleanupUnneeded - Found 0 availableSegments, skipping the cleanup of segments from historicals. This is done to prevent a race condition in which the coordinator would drop all segments if it started running cleanup before it finished polling the metadata storage for available segments for the first time.
docker-druid       | 2018-04-04T15:07:31,718 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorBalancer - [_default_tier]: One or fewer servers found.  Cannot balance.
docker-druid       | 2018-04-04T15:07:31,718 INFO [DatabaseRuleManager-Exec--0] io.druid.metadata.SQLMetadataRuleManager - Polled and found rules for 1 datasource(s)
docker-druid       | 2018-04-04T15:07:44,064 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorLogger - Load Queues:
docker-druid       | 2018-04-04T15:07:47,607 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorLogger - Server[172.18.0.4:8083, historical, _default_tier] has 0 left to load, 0 left to drop, 0 bytes queued, 0 bytes served.
docker-druid       | 2018-04-04T15:08:14,977 WARN [DatabaseSegmentManager-Exec--0] io.druid.metadata.SQLMetadataSegmentManager - No segments found in the database!
docker-druid       | 2018-04-04T15:08:15,921 INFO [TaskQueue-StorageSync] io.druid.indexing.overlord.TaskQueue - Synced 1 tasks from storage (0 tasks added, 0 tasks removed).
docker-druid       | 2018-04-04T15:08:53,973 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Starting coordination. Getting available segments.
docker-druid       | 2018-04-04T15:08:54,501 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Found [0] available segments.
docker-druid       | 2018-04-04T15:08:55,092 INFO [Coordinator-Exec--0] io.druid.server.coordinator.ReplicationThrottler - [_default_tier]: Replicant create queue is empty.
docker-druid       | 2018-04-04T15:08:55,635 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorCleanupUnneeded - Found 0 availableSegments, skipping the cleanup of segments from historicals. This is done to prevent a race condition in which the coordinator would drop all segments if it started running cleanup before it finished polling the metadata storage for available segments for the first time.
docker-druid       | 2018-04-04T15:08:56,109 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorBalancer - [_default_tier]: One or fewer servers found.  Cannot balance.
docker-druid       | 2018-04-04T15:08:56,762 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorLogger - Load Queues:
docker-druid       | 2018-04-04T15:08:57,644 INFO [Coordinator-Exec--0] io.druid.server.coordinator.helper.DruidCoordinatorLogger - Server[172.18.0.4:8083, historical, _default_tier] has 0 left to load, 0 left to drop, 0 bytes queued, 0 bytes served.
docker-druid       | 2018-04-04T15:08:57,900 INFO [DatabaseRuleManager-Exec--0] io.druid.metadata.SQLMetadataRuleManager - Polled and found rules for 1 datasource(s)
docker-druid       | 2018-04-04T15:09:01,542 INFO [TaskQueue-StorageSync] io.druid.indexing.overlord.TaskQueue - Synced 1 tasks from storage (0 tasks added, 0 tasks removed).
docker-druid       | 2018-04-04T15:09:20,775 INFO [LookupCoordinatorManager--2] io.druid.server.lookup.cache.LookupCoordinatorManager - Not updating lookups because no data exists
docker-druid       | 2018-04-04T15:09:29,296 WARN [DatabaseSegmentManager-Exec--0] io.druid.metadata.SQLMetadataSegmentManager - No segments found in the database!
docker-druid       | 2018-04-04T15:09:30,944 INFO [TaskQueue-StorageSync] io.druid.indexing.overlord.TaskQueue - Synced 1 tasks from storage (0 tasks added, 0 tasks removed).

**Comment by ChenShuai1981** [comment]
I met the same issue, any update on it? "One or fewer servers found.  Cannot balance."
