### ISSUE TITLE
SQL: single quotes cannot be identified using json over HTTP

### ISSUE THREAD

**Issue by Zyc1** [druid-io/druid#4938]
It seems single quotes in the where statement cannot be identified.

sql like this:
curl -XPOST -H'Content-Type: application/json' http://172.24.4.202:8082/druid/v2/sql/ -d '{"query":"SELECT * FROM nanzi_timeseries_data_D WHERE station_name='yunnanlu' limit 10"}'

error message:
{"error":"Unknown exception","errorMessage":"org.apache.calcite.runtime.CalciteContextException: From line 1, column 58 to line 1, column 65: Column 'yunnanlu' not found in any table","errorClass":"org.apache.calcite.tools.ValidationException","host":null}

If I add other characters before the quote, it's also been regarded as column name.

**Comment by gianm** [comment]
@Zyc1 it's really the shell that is foiling you. You can see that if you use echo instead of curl, like `echo '{"query":"SELECT * FROM nanzi_timeseries_data_D WHERE station_name='yunnanlu' limit 10"}'`.

You could work around it by escaping the single quotes using shell-escapes, or by saving your query to a file and then using curl's `-d @filename` feature.
