### ISSUE TITLE
HTTP Coordinator lookup thunders coordinator with `enableLookupSyncOnStartup`

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#5018]
`io.druid.query.lookup.LookupReferencesManager#loadAllLookupsAndInitStateRef` thunders the living hell out of the coordinator on a rolling restart of a bunch of nodes and there is no retry in `io.druid.query.lookup.LookupReferencesManager#fetchLookupsForTier`

This is when `enableLookupSyncOnStartup` is enabled

**Comment by himanshug** [comment]
@drcrallen you mean when historicals/peons startup , each of them send one request to coordinator and coordinator is not able to handle that traffic ?

adding @a2l007

**Comment by drcrallen** [comment]
Yes, when you have hundreds of nodes and do a rolling update, a lot of them can call back to the coordinator at the same time. It doesn't seem to like that traffic. And it is especially problematic if the coordinator is having GC issues (not believed to be related) at the time causing either a jvm crash or a net disconnect.

**Comment by himanshug** [comment]
ok, that sounds more of a problem of coordinator not handling the load.. however request for getting lookups for a tier from coordinator (`/druid/coordinator/v1/lookups/<tier>`) is very lightweight so it shouldn't really be troublesome, sounds like problem is somewhere else e.g. true cause of GC. how many jetty threads do you have at coordinator ? 

sidenote: yes, I think https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/query/lookup/LookupReferencesManager.java#L514 can have some retries and a configurable timeout but that is unrelated . it appears you're having problem on the coordinator node rather than historical/peon nodes. @a2l007 please add retries.

**Comment by drcrallen** [comment]
The coordinator should always be counted on to have some form of problem (from a defensive programming standpoint). So I agree a backoff would probably solve or severely reduce the impact of this issue.

Curing the coordinator GC issues is something we are working on.

**Comment by drcrallen** [comment]
@himanshug one thing I have NOT been able to investigate is if there's unexpected pinch points in the leadership securing functionality that can be exacerbated with concurrent requests. No hint yet that is possible but I think this is one of the first things that has a heavy concurrent and time sensitive connection to the leader that is attempted.

**Comment by himanshug** [comment]
dev-sync discussion: @leventov to raise PR adding retries with back-off .
