### ISSUE TITLE
Data just doesn't want to rollup!

### ISSUE THREAD

**Issue by kaytrance** [druid-io/druid#5244]
ok, I am feeling my brains are somewhat leaking out already, because I cannot understand what is happening.

We have our main data source that gathers data from kafka. We decided to create new data source that will use the **same kafka topic**, so this data source will be based on the same data, but only grouped with higher granularity. To do that we left only dimensions that are groupable on higher granularities (because in kafka each event has more fields, but they are event-specific, so we have to exclude them in order for events to be groupable).

So here's out simple data source spec with only 5 dimensions and 4 metrics:
```
{
   "type": "kafka",
   "dataSchema": {
      "dataSource": "new-datasource-1h",
      "parser": {
         "type": "string",
         "parseSpec": {
            "dimensionsSpec": {
               "dimensionExclusions": [],
               "dimensions": ["aaa", "bbb", "ccc", "ddd", "eee"]
            },
            "format": "json",
            "timestampSpec": {
               "column": "timestamp",
               "format": "auto"
            }
         }
      },
      "metricsSpec": [
         {
            "type"       : "count",
            "name"       : "count"
         }, 
         {
            "type"       : "doubleSum",
            "name"       : "val",
            "fieldName"  : "value"
         },
         {
            "name"      : "min_value",
            "type"      : "doubleMin",
            "fieldName" : "value"
         },
         {
            "name"      : "max_value",
            "type"      : "doubleMax",
            "fieldName" : "value"
         }
      ],
      "granularitySpec": {
         "type": "uniform",
         "segmentGranularity": { "type": "duration", "duration": 21600000 },
         "queryGranularity":   { "type": "duration", "duration": 3600000  },
         "rollup": true
      }
   },
   "tuningConfig": {
      "type": "kafka",
      "maxRowsInMemory"  : 250000,
      "maxRowsPerSegment": 15000000,
      "intermediatePersistPeriod": "PT10M",
      "maxPendingPersists": 0,
      "indexSpec": {
         "bitmap": {
            "type": "concise"
         },
         "dimensionCompression": "lz4",
         "metricCompression": "lz4",
         "longEncoding": "longs"
      },
      "buildV9Directly": true,
      "reportParseExceptions": false,
      "handoffConditionTimeout": 0,
      "resetOffsetAutomatically": true,
      "chatThreads": 2,
      "chatRetries": 8,
      "httpTimeout": "PT20S",
      "shutdownTimeout": "PT80S",
      "offsetFetchPeriod": "PT30S"
   },
   "ioConfig": {
      "topic": "parser-out",
      "replicas": 1,
      "taskCount": 4,
      "taskDuration": "PT3600S",
      "consumerProperties": {
         "bootstrap.servers": "xxx1:9092,xxx2:9092,xxx3:9092,xxx4:9092"
      },
      "startDelay": "PT5S",
      "period": "PT30S",
      "useEarliestOffset": false,
      "completionTimeout": "PT5400S",
      "skipOffsetGaps": false
   }
}
```

As data goes I can see that druid only saves dimensions and metrics that I have specified, skipping other data that exist in each real event.

`queryGranularity` in specs is set to `1h`, and I expect that all events in one hour window will be grouped by fields that we defined as dimensions, right?

Well they just do not. I can see that during that one hour I have some grouped events (they have `count` metric > 1), but vast majority of events have `count = 1`. 

One thing that I have noticed is that druid data (rows) that have `count > 1` or even greater have `val` metric = 0. So it seems that `val` even if defined as metric (and should be aggregated) still treated as dimension.

I have tried to modify spec by sending a POST request with new specs having `val` and `value` (just in case) put into `dimensionExclusions` but this does not help as well. I have event tried to put fields into `dimensionExclusions` that are in kafka, and that are not speficied in `dimenstions` with idea that even if I do not want them to be in druid they still somehow affects on whats gets rolled up, but this also didn't helped. In the end I can see that my segments size is huge, but initial idea was to have new data source with aggregated metrics that will result with much smaller sizes for similar timeframe.

Please help!

**Addition**
For example we have two events here, that for some unknown to me reasons were not rolled up:
```
{
   "__time": "2018-01-10T13:00:00.000Z",
   "count": 1,
   "val": 282,
   "max_value": 282,
   "min_value": 282,
   "aaa": "some_value_aaa",
   "bbb": "some_value_bbb",
   "ccc": "some_value_ccc",
   "ddd": "some_value_ddd",
   "eee": "some_value_eee"
},
{
   "__time": "2018-01-10T13:00:00.000Z",
   "count": 1,
   "val": 489,
   "max_value": 489,
   "min_value": 489,
   "aaa": "some_value_aaa",
   "bbb": "some_value_bbb",
   "ccc": "some_value_ccc",
   "ddd": "some_value_ddd",
   "eee": "some_value_eee"
}
```

**Comment by himanshug** [comment]
from a quick scan, it should work fine with the spec you've given above.

- what druid version are you using?
- how did you get the two events, you mentioned above, to verify that events are not being merged?
- events are expected to not merge when they end up going to two different segments. during indexing, they might temporarily be in different segments due to hitting "maxRowsInMemory" but they would be merged before final segment is created for handoff.

**Comment by kaytrance** [comment]
We have `taskCount: 4` what reads input data from `kafka` stream. Each 5 minute about 12M rows is inserted to `kafka` (that will then end up in druid). I also have `maxRowsInMemory  : 250000` and `maxRowsPerSegment: 15000000`. 

In first 5 minutes I see that druid creates empty 4 shards and starts to gather data to them from `kafka`. In that first round of 5 minutes it gathers 12m rows. And on a next round because of `maxRowsPerSegment: 15000000` or `maxRowsInMemory: 250000` a limit-per-segment is hit and segment starts to form in the middle of second 5m-ingestion run.

Answering your questions:
1. version is `0.11`
2. Basically I ran `SELECT * FROM <datasource> WHERE aaa='some_value_aaaa' AND bbb=... ORDER BY __time DESC LIMIT 50` to get individual rows for specific dimension combination. Of course if I ran `groupBy` or `timeseries` I will not see individual rows.
3. If we produce to kafka 12M rows with unique dimensions (but having different `value` metric each time` and have our `queryGranularity` set to `hour`, then in ideal situation I would like to have 1 segment per hour that will hold 12M rows with aggregated metrics for an hour, and `count` equal to 12, right? And since new segment is formed when: 
     - a) task runs longer that `taskDuration`;
     - b) task hit `maxRowsPerSegment` or if post-aggregated rows still > than `maxRowsInMemory`;
     - c) something bad happens;

i think that **b)** is the trouble point in my case, `maxRowsInMemory` in particular, but your `but they would be merged before final segment is created for handoff` troubles me. I will try to increase `maxRowsInMemory` to hold every unique dimension-set-per-row combination (in my case they are the same 12M) and test things out.

My only doubt is that if we ingest data from `kafka` and have `taskCount: 4` does it mean that druid will  create 4 segments already from the start and in ideal situation during an hour I will not see 1 row with `count: 12` for some dimension set, but rather 4 rows having `count: 3`?

**Comment by himanshug** [comment]
Say `number of kafka partitions` = 8 and `taskCount` = 4 
Then Druid KafkaSupervisor would launch 4 KafkaIndexTask that would each consume from 2 kafka topic partitions.
In Druid-0.11.0 each KafkaIndexTask would independently index each kafka-topic-partition assigned to it. That is, it will create a "chain of segments" for each kafka-topic-partition.

So, in this case at least 8 segments would be created per hour (1 per kafka-topic-partition).

"chain of segments" : KafkaIndexTask would read events from one kafka-topic-partition and keep on putting them into a in-memory-segment . Once `maxRowsInMemory` limit is hit, it will persist that in-memory-segment to disk and create a new in-memory-segment to put more data that is being read from that kafka-topic-partition. When `maxRowsInSegment` limit is hit, all the intermediate persisted segments and current in-memory-segment would be merged into a single segment which would be handed off to be loaded by historical eventually.
Note that in `maxRowsInMemory`, "rows" is count of merged rows in in-memory-segment
and in `maxRowsInSegment`, "rows" is total count of merged rows stored in in-memory-segment + other intermediate segments persisted on disk.

Armed with above information...

>i think that b) is the trouble point in my case, maxRowsInMemory in particular, but your but they would be merged before final segment is created for handoff troubles me. I will try to increase maxRowsInMemory to hold every unique dimension-set-per-row combination (in my case they are the same 12M) and test things out.
Not really, intermediate segments persisted on disk due to reaching `maxRowsInMemory` are only temporary and allows you to work with a JVM of smaller heap size. If you have enough heap then you can set `maxRowsInMemory = maxRowsInSegment` , but in most cases that is not appropriate.

>My only doubt is that if we ingest data from kafka and have taskCount: 4 does it mean that druid will create 4 segments already from the start and in ideal situation during an hour I will not see 1 row with count: 12 for some dimension set, but rather 4 rows having count: 3?

When you have `taskCount = 4` , that means you have at least 4 kafka-topic-partitions and at least 4 segments would be created .. so events that came from different kafka-topic-partitions would end up going to different segments for sure.

hope that helps.

However, In upcoming Druid-0.12.0 release, We have changed Druid KafkaIndexingService so that one KafkaIndexTask creates only one "chain-of-segments" and not as many as number of kafka-topic-partitions assigned to it. So, after Druid-0.12.0 , If you have `taskCount = 1` then only 1 KafkaIndexTask would be launched and it will create only one "chain-of-segments" and you would end up with just 1 segments with all rows in merged form into it.

**Comment by kaytrance** [comment]
Great thank you @himanshug for you explanations, they help a lot.
I will close this case for now.

**Comment by kang-junyoung** [comment]
@himanshug 
```
 Note that in maxRowsInMemory, "rows" is count of merged rows in in-memory-segment
and in maxRowsInSegment, "rows" is total count of merged rows stored in in-memory-segment + other intermediate segments persisted on disk.
```
you mean maxRowsInSegment -> maxRowsPerSegment ??!!

**Comment by himanshug** [comment]
> you mean maxRowsInSegment -> maxRowsPerSegment ??!!

Yes
