### ISSUE TITLE
[0.11.0] Time Parsing Extraction Function returning wrong WeekOfTheYear

### ISSUE THREAD

**Issue by pavanab4u** [druid-io/druid#5445]
Time Parsing Extraction Function for input "20171231" returns wrong WeekOfTheYear as "2017-1" instead of "2017-52". Where as it is returning correctly for "20171230".

**Input**
```json
{
	"type": "extraction",
	"dimension": "stats_date",
	"outputName": "Week",
	"extractionFn": {
		"type": "time",
		"timeFormat": "yyyyMMdd",
		"resultFormat": "yyyy-w"
	}
}
```

**Output**
```json
{
  "version" : "v1",
  "timestamp" : "2017-10-02T00:00:00.000Z",
  "event" : {
    "Stats Date" : "20171230",
    "Some Metric" : 0,
    "Week" : "2017-52"
  }
},
{
  "version" : "v1",
  "timestamp" : "2017-10-02T00:00:00.000Z",
  "event" : {
    "Stats Date" : "20171231",
    "Some Metric" : 0,
    "Week" : "2017-1"
  }
}
```

**Comment by gianm** [comment]
Hi @pavanab4u, I think you meant to do `YYYY-w` or `YYYY-ww` rather than `yyyy-w`. Y is year of weekyear and y is year of date. So if you did that then 20171231 would give you `2018-01` which does make more sense.

However there is another wrinkle- this formatter uses java's GregorianCalendar which is not strictly ISO: https://docs.oracle.com/javase/9/docs/api/java/util/GregorianCalendar.html#week_year. ISO reckoning would have said 2017-12-31 is weekyear-week 2017-52. Although in any reckoning, weekyear and calendar year are not always the same, so the 31st of a month could be considered to be in the first week of the next year. Exactly which years this happens for differs from reckoning to reckoning.

Probably ISO reckoning would be preferred, since it's more common in Druid. So it'd be nice to add an option for that. Probably also an option to use joda formatter strings rather than SimpleDateFormat strings, since those aren't compatible either, and joda is also more common in Druid.

Going to change this from a bug to an improvement request since it does not seem like a bug to me anymore.

**Comment by pavanab4u** [comment]
Hi @gianm , makes sense, thanks!

**Comment by gianm** [comment]
Hi @pavanab4u - I also raised #5448 with a patch to add support for joda formats with ISO reckoning, which may also be interesting to you.

**Comment by pavanab4u** [comment]
Hi @gianm This is going to be helpful, thanks !
