### ISSUE TITLE
Improve indexing code to simplify merge and persist operations

### ISSUE THREAD

**Issue by cheddar** [druid-io/druid#55]
The indexing code is getting old and the method of updating the storage format is essentially amounting to writing in an old version and converting up multiple times.  This is less than optimal and not a good sign for future maintenance.

We need to look at the indexing code and fixor it up to make it betterz.

**Comment by xvrl** [comment]
We looked at skipping v8 columns and creating v9 columns directly for Druid 0.7.0. It turns out that creating v8 followed by conversion to v9 is still faster than creating v9 columns directly in the current incarnation of the code, due to the fact that v8 serialization walks the rows once to create all the columns vs. v9 code still requires walking the rows multiple times.

**Comment by erikdubbelboer** [comment]
With https://github.com/druid-io/druid/pull/3688 merged I think this issue can be closed.
