### ISSUE TITLE
Add two classes for two modes of KafkaIndexTask

### ISSUE THREAD

**Issue by jihoonson** [druid-io/druid#5771]
KafkaIndexTask is currently too complicated. One thing making it complicated is that it should support the legacy mode (without incremental publishing) for rolling update. The doc is saying "the legacy mode should be remove from versions greater than 0.12.x", but I think it's worth to keep this for at least one more major release to support rolling update from earlier than 0.12.0 (like 0.11.0 -> 0.13.). 

So, it makes sense for me to separate the codes for two modes of KafkaIndexTask into two different classes even though

- It might be a huge change.
- The class for the legacy mode will be removed once we stop supporting backward compatibility for rolling update.

Any thoughts?

**Comment by gianm** [comment]
Since it sounds like we want to remove the legacy code at some point, I don't think it makes sense to put too much effort into factoring it nicely -- what makes more sense is to focus on making sure the newer code path is understandable, and that things will still make sense after the legacy code path is removed. If refactoring is the best way to accomplish that, then I say go for it.
