### ISSUE TITLE
Merging sharded segments

### ISSUE THREAD

**Issue by michas2** [druid-io/druid#5809]
We are using (kafka) indexing tasks to fill our datasources and would like to use `druid.coordinator.merge.on` to merge segments to a perfect size.

Is this currently possible (with any version of druid)?

From the git log I see the following:

241efa - Sat Jan 13 13:52:37 2018 (#5102):
```
+Note that the Merge Task and Append Task described [here](../../ingestion/tasks.html) will not work as they require
+unsharded segments while Kafka indexing tasks always generated sharded segments.
```

b9b3be - Thu Feb 15 11:57:30 2018 (#5390):
```
-Note that the Merge Task and Append Task described [here](../../ingestion/tasks.html) will not work as they require
-unsharded segments while Kafka indexing tasks always generated sharded segments.
+There is also ongoing work to support automatic segment compaction of sharded segments as well as compaction not requiring
+Hadoop (see [here](https://github.com/druid-io/druid/pull/5102)).
 ```

The second commit changes the first one and also refers to that PR, but as the first one only changes documentation it is probably not the one with the "ongoing work" the text is talking about.

So what is the actual status here?

**Comment by gianm** [comment]
Hi @michas2,

What you are asking is not possible with any version of Druid. But some related things are possible.

Essentially the `druid.coordinator.merge.on` and related "merge" and "append" tasks were created to do merging of segments "horizontally" across the timeline. The idea being that if you have a bunch of single, small hourly segments then they may merge them into larger 4-hourly, 5-hourly, whatever segments. They are limited in that they only work on unsharded segments.

Kafka ingestion (as you may be aware) often creates more than one segment per interval. And also, because it can accept late data, it doesn't make so much sense to do merges "horizontally".

The ongoing work being referred to in the docs is compaction (http://druid.io/docs/latest/ingestion/tasks.html#compaction-task) and auto compaction (#5102). That work can also merge sharded segments "vertically" -- meaning it can do things like merge a dozen small hourly segments _for the same hour_ into a smaller number of hourly segments _for the same hour_. There is enough there in master to try out auto-compaction. And even older versions (ones that have actually been released) have the ability to do manual compaction through the compaction task, or even through Hadoop jobs using the `dataSource` inputSpec.

Future work is intended to include "super compaction", i.e. automatically scaling it out, possibly with an option to do it with or without Hadoop.

The end goal is that you just flip a switch and it happens in the background, regardless of the method of ingestion you originally chose (kafka, batch, something custom, etc).

**Comment by michas2** [comment]
Thanks for the quick and helpful answer!
Question solved. :)
