### ISSUE TITLE
Non-English charset support for Druid Jdbc.

### ISSUE THREAD

**Issue by fanwu72** [druid-io/druid#6548]
Hi team,

The below SQL returns nothing while running with Druid Jdbc. 
However it returns some rows when I change to use Druid Restful API.

`select cache_group, count(1) from table where cache_group = '北京NEW' group by cache_group`

When I remove the condition `where cache_group = '北京NEW'` rows are returned as expected. 

I know that Druid Jdbc is a experimental feature but I will be very happy if someone can figure out the problem and fix this issue.

I am using druid-0.12.1

Best regards,
Ryan

**Comment by gianm** [comment]
@fanwu72 are you still facing this issue with the latest Druid? I haven't looked into it yet, but wondering if it's still relevant. Any interest in contributing a unit test that demonstrates the problem? We could add it to the code base with an `@Ignore` tag just so we have it and can use it to verify if this is fixed in the future.

**Comment by BigRantLing** [comment]
Before you execute the sql, you can recode it to `iso88591`,like below:
``` java
        String sql = "select count(*) from table WHERE keywords = '你好'";
        String recodeSql = new String(sql.getBytes(), Charsets.ISO_8859_1);
        ResultSet result = statement.executeQuery(recodeSql);
```
I think this will solve your problem@fanwu72
